/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yujongheyon_anywheresing_anywhere_openCV */

#ifndef _Included_com_example_yujongheyon_anywheresing_anywhere_openCV
#define _Included_com_example_yujongheyon_anywheresing_anywhere_openCV
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_yujongheyon_anywheresing_anywhere_openCV_PERMISSIONS_REQUEST_CODE
#define com_example_yujongheyon_anywheresing_anywhere_openCV_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_yujongheyon_anywheresing_anywhere_openCV
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_yujongheyon_anywheresing_anywhere_1openCV_loadCascade
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_yujongheyon_anywheresing_anywhere_openCV
 * Method:    detect
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_yujongheyon_anywheresing_anywhere_1openCV_detect
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
